// <auto-generated />
using System;
using DataLayer.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(HrBotContext))]
    partial class HrBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Dals.ApplicationAnswerDal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserApplicationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserApplicationId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("DataLayer.Dals.BotUserDal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("TgId")
                        .HasColumnType("bigint");

                    b.Property<string>("TgName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("TgId")
                        .IsUnique()
                        .HasFilter("\"TgId\" IS NOT NULL");

                    b.ToTable("BotUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2f8b0c4-3c1e-4b5a-9f6e-7c8d9e0f1a2b"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastActivity = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TgId = 319556101L,
                            TgName = "brovko_a"
                        });
                });

            modelBuilder.Entity("DataLayer.Dals.ConditionDal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool?>("CriticalText")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("DataLayer.Dals.HrUserDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("BotUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BotUserId")
                        .IsUnique();

                    b.ToTable("HrUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "TECH BOSS",
                            BotUserId = new Guid("d2f8b0c4-3c1e-4b5a-9f6e-7c8d9e0f1a2b"),
                            Position = "Head of Technology"
                        });
                });

            modelBuilder.Entity("DataLayer.Dals.QuestionDal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VacancyId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VacancyId");

                    b.HasIndex("VacancyId1");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000001-0001-0001-0001-000000000001"),
                            Answer = "{\"Type\":\"yesno_required\",\"Expected\":true,\"UnexpectedAnswerRejectText\":\"We require at least 3 years of software development experience for this position.\"}",
                            OrderNumber = 1,
                            Text = "Do you have at least 3 years of experience in software development?",
                            VacancyId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("10000001-0001-0001-0001-000000000002"),
                            Answer = "{\"Type\":\"text\"}",
                            OrderNumber = 2,
                            Text = "Please describe your experience with C# and .NET technologies.",
                            VacancyId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("10000001-0001-0001-0001-000000000003"),
                            Answer = "{\"Type\":\"yesno\"}",
                            OrderNumber = 3,
                            Text = "Are you comfortable working in an Agile/Scrum environment?",
                            VacancyId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20000001-0001-0001-0001-000000000001"),
                            Answer = "{\"Type\":\"yesno_required\",\"Expected\":true,\"UnexpectedAnswerRejectText\":\"SQL knowledge is essential for this Data Analyst position.\"}",
                            OrderNumber = 1,
                            Text = "Do you have experience with SQL and database querying?",
                            VacancyId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("20000001-0001-0001-0001-000000000002"),
                            Answer = "{\"Type\":\"text\"}",
                            OrderNumber = 2,
                            Text = "Please describe your experience with data visualization tools (e.g., Tableau, Power BI, Python).",
                            VacancyId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("20000001-0001-0001-0001-000000000003"),
                            Answer = "{\"Type\":\"yesno\"}",
                            OrderNumber = 3,
                            Text = "Have you worked with statistical analysis or machine learning before?",
                            VacancyId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("30000001-0001-0001-0001-000000000001"),
                            Answer = "{\"Type\":\"yesno_required\",\"Expected\":true,\"UnexpectedAnswerRejectText\":\"We require at least 2 years of project management experience for this role.\"}",
                            OrderNumber = 1,
                            Text = "Do you have at least 2 years of project management experience?",
                            VacancyId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("30000001-0001-0001-0001-000000000002"),
                            Answer = "{\"Type\":\"text\"}",
                            OrderNumber = 2,
                            Text = "Please describe your experience managing technical teams and software development projects.",
                            VacancyId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("30000001-0001-0001-0001-000000000003"),
                            Answer = "{\"Type\":\"yesno\"}",
                            OrderNumber = 3,
                            Text = "Are you familiar with project management methodologies like Agile, Scrum, or Kanban?",
                            VacancyId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("DataLayer.Dals.UserApplicationDal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastQuestionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BotUserId");

                    b.HasIndex("ChatId");

                    b.HasIndex("LastActivity");

                    b.HasIndex("LastQuestionId");

                    b.HasIndex("StartDate");

                    b.HasIndex("State");

                    b.HasIndex("VacancyId");

                    b.ToTable("UserApplications");
                });

            modelBuilder.Entity("DataLayer.Dals.VacancyDal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultRejectText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("FinishedApplicationText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("HrId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("HrId");

                    b.ToTable("Vacancies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultRejectText = "Thank you for your interest in the Senior Software Developer position. Unfortunately, we have decided to move forward with other candidates at this time. We wish you the best in your job search!",
                            Description = "We are looking for an experienced software developer to join our team. You will work on cutting-edge projects using modern technologies and contribute to building scalable applications.",
                            FinishedApplicationText = "🎉 Congratulations! You have successfully completed your application for the Senior Software Developer position. Our HR team will review your responses and get back to you within 5-7 business days. Thank you for your interest in joining our team!",
                            IsActive = true,
                            IsArchived = false,
                            Title = "Senior Software Developer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultRejectText = "Thank you for applying to the Data Analyst position. After careful consideration, we have decided to proceed with other candidates. We appreciate your time and interest in our company.",
                            Description = "Join our data team as a Data Analyst! You'll work with large datasets, create insightful reports, and help drive data-driven decision making across the organization.",
                            FinishedApplicationText = "✅ Your application for the Data Analyst position has been submitted successfully! We're excited to learn more about your background. Our team will review your application and contact you within 3-5 business days.",
                            IsActive = true,
                            IsArchived = false,
                            Title = "Data Analyst"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultRejectText = "Thank you for your application for the Technical Project Manager role. While your background is impressive, we have chosen to move forward with candidates whose experience more closely aligns with our current needs.",
                            Description = "We're seeking a Technical Project Manager to lead cross-functional teams and deliver complex software projects. You'll coordinate with developers, designers, and stakeholders to ensure successful project delivery.",
                            FinishedApplicationText = "🚀 Thank you for completing your application for the Technical Project Manager position! We're impressed by your interest in leading our technical initiatives. Expect to hear from us within one week regarding next steps.",
                            IsActive = true,
                            IsArchived = false,
                            Title = "Technical Project Manager"
                        });
                });

            modelBuilder.Entity("DataLayer.Dals.ApplicationAnswerDal", b =>
                {
                    b.HasOne("DataLayer.Dals.QuestionDal", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLayer.Dals.UserApplicationDal", "UserApplication")
                        .WithMany("Answers")
                        .HasForeignKey("UserApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("UserApplication");
                });

            modelBuilder.Entity("DataLayer.Dals.ConditionDal", b =>
                {
                    b.HasOne("DataLayer.Dals.QuestionDal", "Question")
                        .WithMany("Conditions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DataLayer.Dals.HrUserDal", b =>
                {
                    b.HasOne("DataLayer.Dals.BotUserDal", "BotUser")
                        .WithOne()
                        .HasForeignKey("DataLayer.Dals.HrUserDal", "BotUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BotUser");
                });

            modelBuilder.Entity("DataLayer.Dals.QuestionDal", b =>
                {
                    b.HasOne("DataLayer.Dals.VacancyDal", null)
                        .WithMany("Questions")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Dals.VacancyDal", "Vacancy")
                        .WithMany()
                        .HasForeignKey("VacancyId1");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("DataLayer.Dals.UserApplicationDal", b =>
                {
                    b.HasOne("DataLayer.Dals.BotUserDal", "BotUser")
                        .WithMany("Applications")
                        .HasForeignKey("BotUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Dals.QuestionDal", "LastQuestion")
                        .WithMany()
                        .HasForeignKey("LastQuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataLayer.Dals.VacancyDal", "Vacancy")
                        .WithMany("Applications")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BotUser");

                    b.Navigation("LastQuestion");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("DataLayer.Dals.VacancyDal", b =>
                {
                    b.HasOne("DataLayer.Dals.HrUserDal", "Hr")
                        .WithMany()
                        .HasForeignKey("HrId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hr");
                });

            modelBuilder.Entity("DataLayer.Dals.BotUserDal", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("DataLayer.Dals.QuestionDal", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("DataLayer.Dals.UserApplicationDal", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("DataLayer.Dals.VacancyDal", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
