// <auto-generated />
using System;
using DataLayer.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(HrBotContext))]
    partial class HrBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Dals.AnswerDal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserApplicationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserApplicationId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("DataLayer.Dals.BotUserDal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("TgId")
                        .HasColumnType("bigint");

                    b.Property<string>("TgName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("TgId")
                        .IsUnique()
                        .HasFilter("\"TgId\" IS NOT NULL");

                    b.ToTable("BotUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2f8b0c4-3c1e-4b5a-9f6e-7c8d9e0f1a2b"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastActivity = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TgId = 319556101L,
                            TgName = "brovko_a"
                        });
                });

            modelBuilder.Entity("DataLayer.Dals.ConditionDal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool?>("CriticalText")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("DataLayer.Dals.HrUserDal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("BotUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BotUserId")
                        .IsUnique();

                    b.ToTable("HrUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "TECH BOSS",
                            BotUserId = new Guid("d2f8b0c4-3c1e-4b5a-9f6e-7c8d9e0f1a2b"),
                            Position = "Head of Technology"
                        });
                });

            modelBuilder.Entity("DataLayer.Dals.QuestionDal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VacancyId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VacancyId");

                    b.HasIndex("VacancyId1");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("DataLayer.Dals.UserApplicationDal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastQuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid>("VacancyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LastQuestionId");

                    b.HasIndex("VacancyId");

                    b.ToTable("UserApplications");
                });

            modelBuilder.Entity("DataLayer.Dals.VacancyDal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultRejectText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("FinishedApplicationText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("HrId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("HrId");

                    b.ToTable("Vacancies");
                });

            modelBuilder.Entity("DataLayer.Dals.AnswerDal", b =>
                {
                    b.HasOne("DataLayer.Dals.QuestionDal", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLayer.Dals.UserApplicationDal", "UserApplication")
                        .WithMany("Answers")
                        .HasForeignKey("UserApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("UserApplication");
                });

            modelBuilder.Entity("DataLayer.Dals.ConditionDal", b =>
                {
                    b.HasOne("DataLayer.Dals.QuestionDal", "Question")
                        .WithMany("Conditions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DataLayer.Dals.HrUserDal", b =>
                {
                    b.HasOne("DataLayer.Dals.BotUserDal", "BotUser")
                        .WithOne()
                        .HasForeignKey("DataLayer.Dals.HrUserDal", "BotUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BotUser");
                });

            modelBuilder.Entity("DataLayer.Dals.QuestionDal", b =>
                {
                    b.HasOne("DataLayer.Dals.VacancyDal", null)
                        .WithMany("Questions")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Dals.VacancyDal", "Vacancy")
                        .WithMany()
                        .HasForeignKey("VacancyId1");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("DataLayer.Dals.UserApplicationDal", b =>
                {
                    b.HasOne("DataLayer.Dals.QuestionDal", "LastQuestion")
                        .WithMany()
                        .HasForeignKey("LastQuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataLayer.Dals.VacancyDal", "Vacancy")
                        .WithMany("Applications")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LastQuestion");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("DataLayer.Dals.VacancyDal", b =>
                {
                    b.HasOne("DataLayer.Dals.HrUserDal", "Hr")
                        .WithMany()
                        .HasForeignKey("HrId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hr");
                });

            modelBuilder.Entity("DataLayer.Dals.QuestionDal", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("DataLayer.Dals.UserApplicationDal", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("DataLayer.Dals.VacancyDal", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
